### ISSUE TITLE
excuse me, I clone the code, but I met a question, why is "planning and fetching data..." constantly loading

### ISSUE THREAD

**Issue by losecanvas** [StevenLyt/mapf-visualizer#2]

**Comment by StevenLyt** [comment]
Hi,

I believe the reason why you encountered the issue is that the request was not sent properly to the backend. I would like to clarify that this repository only contains the frontend (i.e. visualization) part of the project. The backend, which should include the specific MAPF algorithms, is intended to be implemented by you depending on the algorithms you want to use.

If you take a look at line 198 in the `MAPFVisualizer.jsx`, you will see that the backend URL is stored in the `.env` file, which is unique to each individual. I hope this clarifies the issue. Please let me know if you have any further questions. Thank you!

**Comment by losecanvas** [comment]
Appreciate for your reply!
